name: Update Checker

env:
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    UPLOAD_RELEASE: true

on:
    workflow_dispatch:
    schedule:
        - cron: '0 16 */14 * *'

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: AutoTrigger-ActionBot
              uses: bigbugcc/ActionBot@main

            - name: Delete workflow runs
              uses: Mattraks/delete-workflow-runs@main
              with:
                  retain_days: 1
                  keep_minimum_runs: 1

            - name: Remove old Releases
              uses: dev-drprasad/delete-older-releases@master
              continue-on-error: true
              if: env.UPLOAD_FIRMWARE_FOR_RELEASE == 'true' && !cancelled()
              with:
                  keep_latest: 3
                  delete_tags: true
              env:
                  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
